### ISSUE TITLE
Research: How to deploy package to NPM

### ISSUE THREAD

**Issue by isatrio** [abdillahadam20/Shopping-Card#6]
This is no code required, just do a research on how to deploy to a package to the NPM registry. A good start to read 

1. https://docs.npmjs.com/cli/v8/commands/npm-publish
2. https://semver.org/lang/id/spec/v2.0.0.html
3. https://www.conventionalcommits.org/en/v1.0.0/

**Comment by abdillahadam20** [comment]
Untuk research how to deploy package to NPM saya udah baca mas namun masih agak kurang ngerti untuk ngerubah paket ke npm. Kalo yang saya baca itu biasa untuk ngebuat versi untuk setiap sistem yang kita keluarin, kalo misalnya mau nambahin file atau hapus itu biasanya kita rilis versi baru dan untuk di dalemnya apabila sudah di keluarkan tidak boleh di ubah. Kurang lebihnya yang saya tangkep begitu, cmiiw ya mas.

**Comment by isatrio** [comment]
Sebenernya sih package itu nanti biar bisa dipake orang lagi. Gak cuman dipake di kalangan sendiri tinggal `npm install nama-package`. Secara teknis, yang dirimu pahami udah bener kok. Bisa dibaca lagi soal gimana caranya? Nanti begitu kita udah beres sama semuanya, kita bakalan coba publish package ini ke NPM.

Coba-coba aja rilis beta dulu. Hasil akhirnya package ini bisa dilihat di npmjs.com as a beta project.

**Comment by isatrio** [comment]
Ini diriku close aja ya, ganti tiket untuk publish package
